### ISSUE TITLE
Review: ListParticipantsWidget.jsx and UpdateMinorParticipantsWidget.jsx

### ISSUE THREAD

**Issue by wenhaoq20** [bang-software/HACC-Hui-414f23#159]
## Overview

The focus for this code review will be centered around ListParticipantsWidget.jsx and UpdateMinorParticipantsWidget.jsx.
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-004

## Files to review

* [ListParticipantsWidget.jsx](../blob/main/app/imports/ui/components/participant/ListParticipantsWidget.jsx)
* [UpdateMinorParticipantsWidget.jsx](../blob/main/app/imports/ui/components/administrator/UpdateMinorParticipantsWidget.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, October 2, 9:00 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by EvanAraki** [comment]
UpdateMinorParticipantsWidget

JS05: Line 28, _.each used

JS06: Line 59, 64, 86 console.log used

RE-01 There are like 4 separate function definitions in this widget, I'm not sure if that's good coding standards but it seems a bit dense for a single widget. 

DE-06: Again it is very difficult to tell how each function works with no comments and many dense references to numerous prop types and objects. 

-inline style

ListParticipantsWidget

DE01: Code repeats itself multiple times, can be refactored. Especially evident with page rendering portion.

Line 156-159 , 141-142, 125-126
I think these are nested for loops to check if a value appears in a collection... There has to be a better way to do that in JS right?

-inline style

**Comment by wenhaoq20** [comment]
# ListParticipantsWidget.jsx
AR-01: multiple components is called ListParticipants
DE-01, DE-07: multiple repeat calls of setFilter()
JS-01: reusing names like skills, tools, teams
JS-04: prefer arrow functions (line 122, 138, 153, ...)
JS-05: some  functions can be replaced
JS-07: no JSDoc
ES-01: div align={'center'} is not valid
RE-04: need to destructure props in parameter
RE-09: prefer function components

# UpdateMinorParticipantsWidget.jsx
JS-04: prefer arrow functions (line 25, 38, 57,  73, ...)
JS-05: some  functions can be replaced
JS-07: no JSDoc
RE-04: need to destructure props in parameter
RE-09: prefer function components
multiple style declared in render()

**Comment by yongsungm** [comment]
## ListParticipantsWidget.jsx

RE-09: L25 Prefer functions vs. classes for stateless components
DE-05: L132 Unnecessary comment
DE-07: L183, 190, 197, 210, 223, 234 repeated styling
RE-10: Avoid Widget and Card in names
JS-05: L12, 35, 124, 140, 155 Avoid underscore functions. Use ES6 built-in functions


## UpdateMinorParticipantsWidget.jsx

RE-09: L15 Prefer functions vs. classes for stateless components
DE-06: Ensure code is readable. L40 to 54 are nonsense. What is CheckBoxFun, what is evt, MP is an unnecessary abbreviation, p is a meaningless variable name,
JS-05: L04, 28 Avoid underscore functions. Use ES6 built-in functions
JS-06: L64 Avoid console.logs
RE-07: L29, 30 Don't retrieve collection data inside render().
RE-10: Avoid Widget and Card in names

**Comment by sukaryo-heilscher** [comment]
ListP:
DE-01: The different getXs can possibly be consolidated, depends on how the stateless implementation works.
DE-06: Fix the weird import spacing.
DE-08: Background colors should be imports. Also maybe the sticky thing (L57)?
JS-05: Uses Iodash.
RE-04: Change this.props to constants.
RE-06: We agreed on useTracker, yeah?
RE-09: Convert class to function.

UpdateMP:
DE-08: Background colors should be imports.
JS-04: Can convert the numerous functions to arrow functions.
JS-05: Uses Iodash.
JS-06: Uses console.log in download function, but might be fine since it's admin...?
ES-01: Suppresses a warning on L45.
RE-04: Change this.props to constants.
RE-09: Convert class to function.

**Comment by gitCarrot** [comment]
ListParticipantsWidget.jsx

JS-05: Prefer ES6 built-in functions over lodash (underscore) functions.
JS-04: Use arrow functions to simplify and potentially remove the need for binding.
RE-09: The ListParticipantsWidget component maintains state and has lifecycle methods, so it's appropriate as a class. However, for any future stateless components, prefer function components over class components.
DE-05: There's a commented console.log in the getParticipantSkills function.
RE-04: Props can be destructured in the render method for cleaner code.
JS-07: Missing JSDoc for the component and its methods.
ES-01: Inline styling is used throughout the component. Consider using CSS modules or styled-components for maintainability and consistency.

UpdateMinorParticipantsWidget.jsx

JS-05: Usage of lodash with the _.each method in getMinorParticipants.
JS-04: Methods like renderMinorParticipants, download, and submitData could be arrow functions.
AR-01: Use of non-descriptive variables like MP in submitData. More descriptive variable names could enhance code readability.
ES-01: Inline styling is present in this component as well. Consider moving these styles to external stylesheets or using other styling approaches.

**Comment by wenhaoq20** [comment]
# Outcome
 - Use useTracker instead of withTracker, example in NavBar.
- Text-align instead of align. Container instead of div?
- meteor npm install for main branch
- Run acceptance tests when creating pull requests and when approving pull-requests.
- Don't change the database during acceptance testing in order to allow for repeatability.

**Comment by MacabanteJ** [comment]
ListParticipantsWidget.jsx
DE-01: Repeated code segments
JS-04: Use arrow functions
JS-05: Avoid underscore functions
JS-07: No JSDoc
RE-01: Simplify component
RE-04: Destructure props in parameter
RE-09: Prefer functions over classes

UpdateMinorParticipantsWidget.jsx
JS-04: Use arrow functions
JS-06: Avoid console.log()
JS-07: No JSDoc
RE-09: Prefer functions over classes
