### ISSUE TITLE
Review: ListTeamExampleWidget.jsx and ViewTeam.jsx

### ISSUE THREAD

**Issue by wenhaoq20** [bang-software/HACC-Hui-414f23#174]
## Overview

The focus for this code review will be centered around the ListTeamExampleWidget.jsx and ViewTeam.jsx.
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-005

## Files to review

* [ListTeamExampleWidget.jsx](../blob/main/app/imports/ui/components/participant/ListTeamExampleWidget.jsx)
* [ViewTeam.jsx](../blob/main/app/imports/ui/components/administrator/ViewTeam.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, October 9, 9:00 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by EvanAraki** [comment]
**ListTeamExampleWidget:**

DE-01 Line44-65 renderButton() should be refactored. Style and functionality is being assigned in an arbitrary function, this can probably be consolidated to props or maybe an overall arrow function that handles how the form submits its data. 

DE-07 line 70-> If whoever is working on this code has extra time, can probably condense the rendering of the page a little. Seems a bit repetitive but the code is short enough that I don't think a more elegant method is NEEDED.

**ViewTeam**

Relatively clean code im not sure what to say about it. Maybe inline style could use a cleanup and consolidation into a css file.

**Comment by Louie808** [comment]
### ListTeamExampleWidget.jsx
RE-09: Prefer functions vs. classes for stateless components
JS-05: Avoid underscore functions. Use ES6 built-in functions
RE-06: Define constants with useTracker()
RE-07: Doing data retrieval inside render()
RE-10: Avoid Widget and Card in names
DE-00: Inline styling inside the button rendering
DE-01: Buttonrender code can be reduced. its only changing the string used for the button
RE-01: Code is split between rendering in mobile and pc. Should 2 subfunctions be made to group?
RE-00: Convert to bootstrap
<hr>

### ViewTeam.jsx
RE-06: Define constants with useTracker()
RE-00: Convert to bootstrap

**Comment by wenhaoq20** [comment]
# ListTeamExampleWidget.jsx
DE-03: removed commented out imports
JS-04: prefer arrow function
JS-05: avoid _ functions (line 47, 50, 51)
JS-06: avoid console.log (line 22, 31)
JS-07: no JSDoc
RE-04: destructure props
RE-06: change to useTracker
RE-09: convert from class component to functional

# ViewTeam.jsx
AR-01 ViewTeam and ViewTeams
DE-03: remove commented out console.log and unused imports(line 4, 26, 92)
JS-04: prefer arrow function (line 17, line 22)
JS-07: no JSDoc
RE-06: change to useTracker

**Comment by gitCarrot** [comment]
- ListTeamExampleWidget.jsx

JS-04: Convert methods like handleClick and renderButton to arrow functions.
JS-05: Replace underscore methods with native JavaScript methods where possible.
JS-07: Add JSDoc comments to describe functions/components.
RE-00: Bootstrap convertion needed
RE-04: Destructure props in the render method to simplify their usage in the component.
RE-09: Consider converting the class component to a functional component and use hooks for state management.

- ViewTeam.jsx

JS-05: Consider using native JavaScript array methods instead of underscore methods.
JS-07: Add JSDoc comments 
RE-00: Bootstrap convertion needed
RE-04: Destructure props in the component parameter to clean up the code.
RE-06: Ensure constants are cleanly defined when using useTracker().

**Comment by yongsungm** [comment]
## ListTeamExampleWidget.jsx

RE-09: L14 Prefer functions vs. classes for stateless components
RE-10: Avoid widget and card in names
JS-06: L22 avoid console.logs
DE-05: L5 Unnecessary comment
JS-05: L47, 50 Avoid underscore functions. Use ES6 built-in functions


## ViewTeams.jsx

JS-05: L94 Avoid underscore functions. Use ES6 built-in functions
DE-05: L69, 92 Unnecessary comment

**Comment by sukaryo-heilscher** [comment]
ListT:
DE-01: Weird duplication going on for pc vs mobile.
DE-05: L5 commented out import.
JS-05: Uses Underscore.
JS-06: L22, 31 console.log
RE-04: Change this.props to constants.
RE-09: Convert class to function.


ViewT:
DE-06: L34 weird spacing.
DE-08: L18 Background colors should be imports. 
JS-05: Uses Iodash.
ES-01: ESLint suppression L69.
RE-06: Change to useTracker.
RE-09: Convert class to function.

Why is it all the way to the left when you click on it?

**Comment by wenhaoq20** [comment]
# Outcome of the meeting

- ListTeamExampleWidget.jsx: Retrieve collection data in UseTracker, pass props through function calls to handle click.
- Uniforms: Stick to uniforms components and style it.
