### ISSUE TITLE
Review:  ListSuggestionsCard.jsx and ListTeamsWidget.jsx

### ISSUE THREAD

**Issue by wenhaoq20** [bang-software/HACC-Hui-414f23#205]
## Overview

The focus for this code review will be centered around ListSuggestionsCard.jsx and ListTeamsWidget.jsx
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-009

## Files to review

* [ListSuggestionsCard.js](../blob/main/app/imports/ui/components/administrator/ListSuggestionsCard.jsx)
* [ListTeamsWidget.jsx](../blob/main/app/imports/ui/components/participant/ListTeamsWidget.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, November 6, 9:00 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by EvanAraki** [comment]
### ListSuggestionsCard.jsx
JS-06: L26, 42, 70 remove console.log()
- convert to booststrap, usetracker, etc (default stuff)

### ListTeamsWidget.jsx
DE-01: L17, 26, 33, 40 can be refactored into a helper function to reduce duplicate code.  

const getRelatedItems = (x, y) => team => {
 const teamID = team._id;
 const relatedDocs = x.find({ teamID }).fetch();
 return relatedDocs.map(doc => y.findDoc(doc.id).name);
};

const getTeamChallenges = getRelatedItems(TeamChallenges, Challenges);
....

L74 arrow functions in render. move outside of render.

**Comment by Louie808** [comment]
### ListSuggestionsCard.js
RE-09: Prefer functions vs. classes for stateless components
RE-06: Define constants with useTracker()
DE-00: Inline styling
RE-00: Convert to bootstrap
<hr>

### ListTeamsWidget.jsx
DE-01: Refactor to reduce duplication?
RE-09: Prefer functions vs. classes for stateless components
RE-00: Convert to bootstrap

**Comment by yongsungm** [comment]
## ListSuggestionsCard.jsx

RE-10: Avoid Widget and Card in names.
RE-09: L15 Prefer functions vs. classes for stateless components
DE-05: L70 unnecessary comment
JS-04: L17, 40, 69 Use arrow functions when appropriate
RE-04: L77, 81, 84, 88, 89 Destructure props in component parameter.
JS-06: L26, 42 Avoid console.logs

Line 103 use useTracker instead of withTracker


## ListTeamsWidget.jsx

RE-10: Avoid Widget and Card in names.
RE-09: L46 Prefer functions vs. classes for stateless components
JS-04: L47 Use arrow functions when appropriate
RE-07: L76-80 Don't retrieve collection data inside render()

**Comment by MacabanteJ** [comment]
ListSuggestionsCard.jsx
RE-04: L88, 89, destructure .props
RE-06: use useTracker() instead of withTracker()
RE-09: functions instead of classes
RE-10: Card in name
JS-06: L26, 42, 70 - remove console.log

ListTeamsWidget.jsx
RE-07: Don't retrieve data in render()
RE-09: function over class components

**Comment by wenhaoq20** [comment]
# ListSuggestionCard.jsx
DE-05: remove unused console.log (line 70)
JS-04: use arrow function (line 17, 40)
JS-06: remove console.logs (line 26, 42, 70)
JS-07: missing JSDoc
RE-04: destructure props in component parameter
RE-09: convert to functional component

# ListTeamsWidget.jsx
JS-07: missing JSDoc
RE-04: destructure props in component parameter
RE-09: convert to functional component
ES-02: () around team in the get functions?
Also wondering why the getTeamxxx functionis are outside of the class component

**Comment by gitCarrot** [comment]
ListSuggestionsCard.jsx Review:
AR-01: File naming follows convention.
DE-03: Remove commented console.log in the render method.
JS-04: Convert removeItem and addSuggestion into arrow functions.
JS-06: Remove console.log statements used for debugging.
RE-04: Destructure props at the start of the render method 
RE-09: Consider converting to a functional component with hooks for state management.
ListTeamsWidget.jsx Review:
AR-01: File naming follows convention.
DE-05: Consider adding comments for helper functions to explain their purpose and usage.
JS-07: Add JSDoc comments for helper functions (getTeam, getTeamChallenges, etc.).
RE-09: Given the simplicity, consider converting from a class to a functional component.

**Comment by sukaryo-heilscher** [comment]
ListSug:
DE-05: Delete L70 comment.
DE-08: L76 Colors should be imports. Also maybe export the swal confirm thing (rewriting so it takes a function to execute)?
JS-04: Covert class functions to arrow functions.
RE-04: Destructure props.
RE-06: Put collection calls in useTracker.
RE-09: Convert class to function.

L 35 'You canceled the deletion!' sounds too happy. Prefer 'Deletion canceled.' or some such.

ListTea:
DE-06: L43 Should have a newline before the return. Also, why have const closed in render?
RE-04: Destructure props.
RE-06: Put collection calls in useTracker.
RE-09: Convert class to function.
