### ISSUE TITLE
Review: SuggestToolSkillWidget.jsx and InterestedParticipantCard.jsx

### ISSUE THREAD

**Issue by wenhaoq20** [bang-software/HACC-Hui-414f23#206]
## Overview

The focus for this code review will be centered around SuggestToolSkillWidget.jsx and InterestedParticipantCard.jsx

Please pay attention to:
* Javascript issues
* React components

## Review Branch

review-010

## Files to review

* [SuggestToolSkillWidget.jsx](../blob/main/app/imports/ui/components/participant/SuggestToolSkillWidget.jsx)
* [InterestedParticipantCard.jsx](../blob/main/app/imports/ui/components/participant/InterestedParticipantCard.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, November 13, 9:00 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by EvanAraki** [comment]
### SuggestToolSkillWidget.jsx

JS-01: Confusing variable names: (fref, formRef)
withtracker -> useTracker

### InterestedParticipantCard.jsx

JS-06: Remove console.log L17, 25, 26, 27, 30, 33, 38, 41, 45, 47, 56, 59, 61, 65, 68
DE-01: add/remove member buttons can be refactored

**Comment by Louie808** [comment]
### SuggestToolSkillWidget.js
RE-09: Prefer functions vs. classes for stateless components
RE-06: Define constants with useTracker()
RE-07: Doing data retrieval inside render()
DE-00: Inline styling
RE-00: Convert to bootstrap
<hr>

### InterestedParticipantCard.jsx
DE-01: Refactor to reduce duplication
RE-09: Prefer functions vs. classes for stateless components
DE-00: Inline styling
RE-00: Convert to bootstrap

**Comment by sukaryo-heilscher** [comment]
SuggToolSkillW:
ES-01: L57 eslint suppression.
RE-04: Destructure props.
RE-06: Change to useTracker.
RE-09: Convert class to function.



InterestParticipantC:
DE-05: Clean up console comments.
DE-06: L168,175 and 188,194 These ternaries can be combined.
DE-07: Buttons are duplicated but I'm not sure the reasoning behind it.
DE-08: L77,91,102.170,177,183 Colors should be imports.
ES-01: L169,176,182,189,199 eslint suppressions.
RE-04: Destructure props.
RE-06: Put collection calls in useTracker.
RE-09: Convert class to function.

**Comment by wenhaoq20** [comment]
# SuggestToolSkillWidget.jsx
JS-04: convert to arrow function (line 28)
JS-07: missing JSDoc
DE-03: remove commented out console.log (line 29)
RE-04: Need to destructure props in component parameter
RE-06: Convert to useTracker
RE-09: Convert from class to functional component
RE-10: Remove Widget from the username
ES-01: fix the max-len next line

# InterestedPartcipantCard.jsx
JS-04: convert to arrow function (line 16, 24, 55, 76, 81)
JS-07: missing JSDoc
ES-01: refactor the line that uses eslint-disable-next-line max-len (line 168-200)
DE-03: removed commented out console.logs (line 25-27 etc)
DE-04: seperate out the modal to a new file (line 128-165)
RE-04: Need to destructure props in component parameter
RE-09: Convert from class to functional component

**Comment by gitCarrot** [comment]
## SuggestToolSkillWidget.jsx
JS-03: Deconstructing this.props in the render method for clarity.
JS-04: Arrow Functions: Convert the submit method and other appropriate methods to arrow functions.
JS-06: Avoid console.logs: Remove commented console.log in submit method.
RE-04: Destructure props in the render method
RE-09: Conversion into a function component.
## InterestedParticipantCard.jsx
JS-04: Arrow Functions: Convert methods like isAdded, handleClick, and removeDev to arrow functions.
RE-06: Optimize Method: Consider refactoring or optimizing the isAdded method for better performance and readability.
RE-09: Functional Component needed
