### ISSUE TITLE
Review: Navbar.jsx and Footer.jsx

### ISSUE THREAD

**Issue by yongsungm** [bang-software/HACC-Hui-414f23#32]
## Overview

The focus for this code review will be centered around Navbar.jsx and Footer.jsx
Please pay attention to:
* Javascript issues
* React components

## Review Branch

review-001

## Files to review

* Navbar.jsx
* Footer.jsx

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, September 11, 9:00 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by Louie808** [comment]
### Footer.jsx
RE09: use function instead of classes
RE07: Retrieves collection data inside render()
Make Navbar more reactive 
- adjust accordingly to window size, using bootstrap breakpoints etc. 
- when navbar exceeds certain item limit.
  - combine user and admin items into possible dropdowns 
  - make more organized categories
<hr>

### Navbar.jsx
RE09: use function instead of classes
<hr>

### App
Organize the app directory directories
- Visually cluttered

**Comment by yongsungm** [comment]
## Navbar.jsx

DE-01 L25-162 A lot of this code is repeated in SideBar.js
DE-04 L8, 15, 23, 36, 37, 110-114, 124, 125 commented out code
RE-07 L28-35 retrieving collection data in the render method
RE-09 L21 functions preferred for stateless components

## Footer.jsx

RE-09 functions preferred for stateless components

**Comment by MacabanteJ** [comment]
Navbar.jsx
DE-01:
Can refactor Navbar items using an array of the inputs and looping through all items, i.e. storing to, key, and menu_title
DE-03:
Dead imports - 8, 15
Unused variables - 36, 37
Unused code segments - 109 to 114, 123 to 124
JS-06:
Unnecessary console logs - 23
RE-09: Function paradigm

Footer.jsx
Push to be bottom of every page
RE-09: Function paradigm

**Comment by wenhaoq20** [comment]
# Navbar:
- should use functional component
- remove commented out code (ex. 36-37, 110-114, 124-125)
- deconstruct this.props to like const {currentUser, canCreateTeams} = this.props
- change the ternary with empty string to && 
- maybe create separate functions for admin and user rendering

# Footer:
- should use functional component
- should be at the bottom of the overall page
- styling with bootstrap component

**Comment by sukaryo-heilscher** [comment]
NavBar:
DE-01: The first few 'Menu.Item's can be consolidated into the same function call with different parameters. (Although when we convert to bootstrap it'll probably look way different.)
DE-03: There's old commented out bits of code that could be removed.
RE-01: Perhaps divide NavBar into 2 components for Admin and Non-Admin.
RE-03: Should be exported as NavBar.
RE-09: Should be a function.

Obviously needs to be Bootstraped. Make sure it's adjustable to narrow windows.

Footer:
RE-09: Should be a function.

Obviously needs to be Bootstraped.

**Comment by gitCarrot** [comment]
## Navbar.jsx:

1. Component Structure:

- Convert to a functional component.
- 
2. Optimization:

- Reduce code repetition; consider shared utility for Navbar.jsx and SideBar.js.
- Refactor Navbar items using looping.
- 
3. Code Cleanliness:

- Remove commented out code, dead imports, and unused variables.
- Remove unnecessary console.log.
- 
4. UI/UX:

- Improve reactivity for various window sizes.
- Group items into dropdowns when exceeding limits.
- Deconstruct this.props for clarity.
- Refactor conditional rendering.



## Footer.jsx:

Component Structure:

- Convert to a functional component.
- 
Styling:

- Ensure position at the page's bottom.
- Consider using Bootstrap for styling.

**Comment by yongsungm** [comment]
## Outcome of review meeting

Create an issue to fix Navbar.jsx
Create an issue to fix Footer.jsx
