### ISSUE TITLE
Review: ProfileWidget.jsx and YourTeamsWidget.jsx

### ISSUE THREAD

**Issue by wenhaoq20** [bang-software/HACC-Hui-414f23#65]
## Overview

The focus for this code review will be centered around the ProfileWidget.jsx and YourTeamsWidget.jsx.
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-003

## Files to review

* [ProfileWidget.jsx](../blob/main/app/imports/ui/components/participant/ProfileWidget.jsx)
* [YourTeamsWidget.jsx](../blob/main/app/imports/ui/components/participant/YourTeamsWidget.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, September 25, 9:00 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by EvanAraki** [comment]
**YourTeamsWidget**
DE-06 needs documentation to label conditional segments of code (eg: line 47, after about 10 seconds its relatively easy to tell that its checking for non-compliance but its not very readable.)

inline-style

**ProfileWidget**

DE-06 Line 20 function: buildTheModel: Why is this object called model
JS-05 Line 22, avoid using _.map

inline-style

**Comment by yongsungm** [comment]
## ProfileWidget.jsx

RE-09: L18 Prefer functions vs. classes for stateless components
DE-05: L32 Unnecessary comment
JS-05: L22 Avoid underscore functions. Use ES6 built-in functions
RE-10: Avoid Widget and Card in names


## YourTeamsWidget.jsx

RE-09: L24 Prefer functions vs. classes for stateless components
DE-05: L33 Unnecessary comment
RE-10: Avoid Widget and Card in names
JS-05: L32, 129 Avoid underscore functions. Use ES6 built-in functions

**Comment by wenhaoq20** [comment]
# ProfileWidge
JS-07: missing JSDoc for the component
JS-04: use arrow functions
JS-05: avoid loadash (line 22)
RE-04: props are not destructured in the parameter
RE-08: file name does not match with its class name
inconsistent styling: some component uses css and some are inline

# YourTeamsWidget
AR-01: confusing naming, YourTeamsCard and YourTeamsWidget
JS-04: use arrow functions
JS-05: avoid using loadash (line 32, 129)
RE-04: props are not destructured in the parameter
ES-01: div align

**Comment by sukaryo-heilscher** [comment]
Profile:
JS-01: Minor thing, but is the "The" in buildTheModel necessary?
JS-05: Uses Iodash in buildTheModel function.
RE-04: Change this.props to constants.
RE-09: Convert class to function.
Have tests... doi.

Teams:
DE-06: What is this whitespacing?! I feel like I'll hurl.
DE-08: The "you haven't read the rules" thing can probably be pulled out and made an import, as I've seen it in other places.
JS-05: Uses Iodash in getTeamParticipants function.
ES-01: Couple errors that'll be cleaned up in the conversion process.
RE-04: Change this.props to constants.
RE-09: Convert class to function.
Have tests... doi.


RE-06: Wait, withTracker? I thought we were supposed to use useTracker? Or am I tripping?

**Comment by MacabanteJ** [comment]
ProfileWidget.jsx

AR-01: I’m confused that it’s ProfileWidget.jsx but the class is EditProfileWidget

RE-01: Consider splitting into ProfileWidget.jsx and another for functionality of EditProfileWidgetCon.
RE-04: Destructure .props calls in buildTheModel() (if possible)
RE-09: Convert to function
RE-10: Named with widget

YourTeamsWidget.jsx

ES-01: 49, 63 - align property not allowed on divs

RE-04: Destructure .props calls
RE-07: Entire class is defined within the render() method, which does not seem reactive
RE-09: Convert to function
RE-10: Named with widget

**Comment by Louie808** [comment]
### ProfileWidget.jsx
RE-09: Convert class to function
JS-05: Uses Iodash in buildTheModel function
RE-04: Change this.props to constants

<hr>

### YourTeamWidget.jsx
RE-09: Convert class to function
RE-10: Widget and Card in names
JS-05: Uses underscore functions. Use ES6 built-in functions

DE-01? : I noticing that our file structure uses Widgets as components files, and is used inside the page files. Can we reduce the files we have by almost half by just removing widgets and placing it's contents inside the page files instead?

**Comment by wenhaoq20** [comment]
# Outcome of this meeting

- Use UseTracker instead of WithTracker. (Ask Moore about this.)
- For now don't bother combining components. Make seperate issues later.
- Combine issues for pages and their respective widgets.
- Change js files with render functions to jsx.
- Destructure props (reduce "this.props" usage).
- Will address these problems when working on these two files.
- Try for 2 pages if not 3. Minimum is 1.

**Comment by gitCarrot** [comment]
ProfileWidget.jsx

AR-01: The file name is ProfileWidget.jsx, but the class is named EditProfileWidget. It's good practice to have the file name match the primary exported class/component name.
RE-04: In the buildTheModel() method, destructure the .props calls for better clarity and concise code.
RE-07: The <Link> component is wrapped inside the <Button> component. This might cause issues with event propagation. Consider having the <Link> wrap the <Button> instead.
RE-09: If possible, convert this class component to a functional component using hooks for more modern React practices.

YourTeamsWidget.jsx
ES-01: Lines 49 and 63: The align property is not allowed on div elements. Consider using CSS styling or flexbox to achieve the desired alignment.
RE-03: The function getTeamParticipants inside the render() method can be moved outside the class or converted to a class method. This avoids recreating the function every time render() is called.
RE-06: There are multiple conditional renderings in the render() method. Consider breaking these out into their own smaller, functional components to simplify the main component.
RE-09: If possible, convert this class component to a functional component using hooks for more modern React practices.
